app:
  host: 127.0.0.1:8080
  env: local
auth:
  expires: 2592000s
  secret: $AUTH_SECRET
  token_name: Bearer
  excepts:
    - api/client/oauth/token
  lookup:
    - "header:Authorization"
    - "query:token"
    - "cookie:token"
    - "form:token"
loggers:
  default: beehive
  beehive:
    file: ./logs/beehive.log
    level: info
    formatter: json
database:
  maxIdle: 10
  maxLifetime: 10m
  maxConns: 30
  default: beehive
  beehive:
    host: $DATABASE_BEEHIVE_HOST
    port: $DATABASE_BEEHIVE_PORT
    user: $DATABASE_BEEHIVE_USER
    password: $DATABASE_BEEHIVE_PASSWORD
    name: $DATABASE_BEEHIVE_NAME
    charset: utf8mb4
