app:
  host: 127.0.0.1:8081
  env: local
oauth:
  expires: 2592000
  secret: MP^go7Kx&eHvsEMafpB66vFp
  token_name: Bearer
  excepts:
    - api/client/oauth/token
  lookup:
    - "header:Authorization"
    - "query:token"
    - "cookie:token"
    - "form:token"
loggers:
  beehive:
    file: ./logs/beehive.log
    level: info
    formatter: json
database:
  maxIdle: 10
  maxLifetime: 10m
  maxConns: 30
  default: beehive
  beehive:
    host: 127.0.0.1
    port: 3306
    user: root
    password: gordon
    name: beehive
    charset: utf8mb4
